image: openmc/openmc:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - apt update
  - apt install -y python3-venv
  - python -m venv venv
  - source venv/bin/activate

build-job:
  stage: build
  script:
    - pip install -U pip
    - pushd /opt/openmc
    - pip install -e .
    - popd
    - pip install .[test]

test-job:
  stage: test
  script:
    - pytest tests
